# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3be56e0012cad20fe2dbc356815d311b119fbf42eeefa6d19b4f46fc1c2a4666c77373adacece951bed0dbf0f874f54319128228eb539a260abe2beb1e630f5b

test:
  secret_key_base: 8e6d9db1188adbe802dec92e06c7a50247a66f252bda43d17c4c78e3c6cf7232a3f1a9dfeca761aa987dad560f6452e6c32f39fe96c33260eb6b7e7672a0f0cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
